namespace Grapes.Api.Models;

public class Seeder
{
    private readonly ApplicationContext _context;

    public Seeder(ApplicationContext context) => _context = context;

    public void Seed()
    {
        var grapes = new[] {
            new Grape("Agiorgitiko"),
            new Grape("Aglianico"),
            new Grape("Airén"),
            new Grape("Albariño","Alvarinho"),
            new Grape("Alicante Bouschet"),
            new Grape("Aligoté"),
            new Grape("Arinto"),
            new Grape("Arneis"),
            new Grape("Assyrtiko"),
            new Grape("Baga"),
            new Grape("Barbera"),
            new Grape("Blaufränkisch"),
            new Grape("Bonarda"),
            new Grape("Brachetto"),
            new Grape("Cabernet Franc"),
            new Grape("Cabernet Sauvignon"),
            new Grape("Carignan"),
            new Grape("Carménère"),
            new Grape("Castelão"),
            new Grape("Catarratto"),
            new Grape("Catawba"),
            new Grape("Chardonnay"),
            new Grape("Chasselas"),
            new Grape("Cinsault"),
            new Grape("Colombard"),
            new Grape("Concord"),
            new Grape("Cortese"),
            new Grape("Corvina"),
            new Grape("Cserszegi Fűszeres"),
            new Grape("Dolcetto"),
            new Grape("Encruzado"),
            new Grape("Erbaluce"),
            new Grape("Falanghina"),
            new Grape("Fernão Pires"),
            new Grape("Frappato"),
            new Grape("Friulano"),
            new Grape("Furmint"),
            new Grape("Gaglioppo"),
            new Grape("Gamay"),
            new Grape("Garganega"),
            new Grape("Gewürztraminer"),
            new Grape("Godello"),
            new Grape("Graševina"),
            new Grape("Grechetto"),
            new Grape("Grenache"),
            new Grape("Grillo"),
            new Grape("Grüner Veltliner"),
            new Grape("Listán Negro"),
            new Grape("Loureiro"),
            new Grape("Malbec"),
            new Grape("Malvasia Fina"),
            new Grape("Marsanne"),
            new Grape("Melon"),
            new Grape("Mencía"),
            new Grape("Merlot"),
            new Grape("Monastrell", "Mourvèdre"),
            new Grape("Moschofilero"),
            new Grape("Muscadine"),
            new Grape("Muscat Blanc"),
            new Grape("Muscat of Alexandria"),
            new Grape("Müller-Thurgau"),
            new Grape("Nebbiolo"),
            new Grape("Negroamaro"),
            new Grape("Nerello Mascalese"),
            new Grape("Nero d’Avola"),
            new Grape("Norton"),
            new Grape("Palomino Fino"),
            new Grape("Pedro Ximénez"),
            new Grape("Petit Verdot"),
            new Grape("Petite Sirah"),
            new Grape("Picpoul"),
            new Grape("Pinot Blanc"),
            new Grape("Pinot Gris"),
            new Grape("Pinot Meunier"),
            new Grape("Pinot Noir"),
            new Grape("Pinotage"),
            new Grape("Refosco"),
            new Grape("Ribolla Gialla"),
            new Grape("Rkatsiteli"),
            new Grape("Roussanne"),
            new Grape("Sagrantino"),
            new Grape("Sangiovese"),
            new Grape("Sauvignon Blanc"),
            new Grape("Savatiano"),
            new Grape("Schiava"),
            new Grape("Silvaner", "Sylvaner"),
            new Grape("St. Laurent"),
            new Grape("Syrah"),
            new Grape("Sémillon"),
            new Grape("Tempranillo"),
            new Grape("Torrontés"),
            new Grape("Touriga Franca"),
            new Grape("Touriga Nacional"),
            new Grape("Trebbiano Toscano"),
            new Grape("Verdejo"),
            new Grape("Verdelho"),
            new Grape("Verdicchio"),
            new Grape("Vermentino"),
            new Grape("Vernaccia di San Gimignano"),
            new Grape("Vidal"),
            new Grape("Viura"),
            new Grape("Xarel-lo"),
            new Grape("Xinomavro"),
            new Grape("Zinfandel"),
            new Grape("Zweigelt", "Primitivo"),
            new Grape("Agiorgitiko"),
        };

        if (!_context.Grapes.Any())
        {
            _context.Grapes.AddRange(grapes);
            _context.SaveChanges();
        }
    }
}